### PR TITLE
tooling(webpack): move to dedicated folder

### PR DESCRIPTION
**Pull request by evenstensberg**
If you want med to help you create better configs with different targets, I can do that (dev, prod).

### CODE REVIEW

**Comment by duttonw** [comment]
Hi @evenstensberg , Could you explain how this works?

**Comment by evenstensberg** [comment]
It just moves the webpack config file to a folder (`.webpack`). Webpack will figure out the config resides there. Makes project structure cleaner.

**Review by duttonw — APPROVED** [review]

**Comment by evenstensberg** [comment]
Lmk if you need more assistance

**Comment by duttonw** [comment]
@evenstensberg , best to enable github actions when you fork so that others can see that the workflow passes and merge quicker. https://github.com/evenstensberg/formio/actions

**Comment by evenstensberg** [comment]
I think the action only can run on your end based on the failing actions in my fork.

**Comment by duttonw** [comment]
Good point. I need to make the premium private npm package be optional for building so it can run on normal public mirrors. Most of the components being built/tested don't need it.

**Comment by evenstensberg** [comment]
Ok. The build seems to be running now, but you need to do something in your CI. Also, I dont recommend publishing packages in PRs

**Comment by duttonw** [comment]
Have done an update to not run the last to jobs if they don't have secrets set, also made @formio/preimium optional so it can run for users who don't have access to the formio non-foss bits.  (may need a little more testing of develop to see)

The last 2 jobs update a binary repo which could be linked to npmjs for distribution as well as a cdn repo when a 'tag' is made only. 

This is to ensure that this repo is as light as possible by only holding source code**




** sadly gh-pages is a binary branch which needs 'resets' once an a while to keep the git repo trimmed down to size.

**Comment by evenstensberg** [comment]
Okay. Lmk if I can be of more help with your project 👋🏾

**Comment by duttonw** [comment]
@evenstensberg , i've fixed up develop to now build without pushing to 'binary' repos as well as ensure that premium formio package does not fail the build either. Can you confirm this on your repo please.

**Comment by evenstensberg** [comment]
Screenshot 2023-07-31 at 19 15 00

**Comment by evenstensberg** [comment]
Screenshot 2023-07-31 at 19 20 48

**Comment by duttonw** [comment]
@evenstensberg  can you pull again, I've made it check if secrets exists and skip pushing the minified files to another repo if not set. This should allow other peoples builds to be successful.

**Pull request merged**
